name: TipJar Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tip-jar-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Aptos CLI
      uses: ./.github/actions/setup-aptos-cli

    - name: Build Forklift
      working-directory: packages/forklift
      run: |
        npm ci
        npm run build

    - name: Run Example TipJar Tests
      working-directory: packages/example-tip-jar
      run: |
        npm ci
        npm test
